### ISSUE TITLE
Invalid csv/url

### ISSUE THREAD

**Issue by e-dorigatti** [synapta/public-contracts#56]
The downloader crashed with the following stacktrace:

```
 [Error: Invalid opening quote at line 8056]
 
 /home/user/public-contracts/ext/downloader.js:317
             for (var i = 0; i < csv_array.length; i++) {
                                          ^
 TypeError: Cannot read property 'length' of undefined
     at /home/user/public-contracts/ext/downloader.js:317:42
     at null. (/home/user/public-contracts/ext/node_modules/csv/node_modules/csv-parse/lib/index.js:67:14)
     at EventEmitter.emit (events.js:95:17)
     at Parser._transform (/home/user/public-contracts/ext/node_modules/csv/node_modules/csv-parse/lib/index.js:161:17)
     at Transform._read (_stream_transform.js:179:10)
     at Transform._write (_stream_transform.js:167:12)
     at doWrite (_stream_writable.js:223:10)
     at writeOrBuffer (_stream_writable.js:213:5)
     at Writable.write (_stream_writable.js:180:11)
     at /home/user/public-contracts/ext/node_modules/csv/node_modules/csv-
```

this is row 8056 of `single.csv`

```
00146470471,http://asp.urbi.it/urbi/progs/urp/fecore01.sto?CPT=N&FileContesto=UR&SottoContesto=OpenData&DB_NAME=n201246&NDFH=440264&TDFH=OPEN1&PRFH=DATASET119&MPFH=1&AEFH=EYIEVSRUENTPKUIGZZEFGVJYCKOLDNOGIYSSGYFWCVDQSWDKUAF1LXQIKMR119NDBLSREBYIAGJL1YOP_N201246F201246&FNFH=dataset_2014_L190.xml",1
```

grepping that url returned

```
./data/download/latest/00146470471/86090a12c39a3d9a1c554172468178859fae0181.xml:<urlFile><![CDATA[http://asp.urbi.it/urbi/progs/urp/fecore01.sto?CPT=N&FileContesto=UR&SottoContesto=OpenData&DB_NAME=n201246&NDFH=440264&TDFH=OPEN1&PRFH=DATASET119&MPFH=1&AEFH=EYIEVSRUENTPKUIGZZEFGVJYCKOLDNOGIYSSGYFWCVDQSWDKUAF1LXQIKMR119NDBLSREBYIAGJL1YOP_N201246F201246&FNFH=dataset_2014_L190.xml]]></urlFile>
./data/download/latest/GET.csv:GET,http://asp.urbi.it/urbi/progs/urp/fecore01.sto?CPT=N&FileContesto=UR&SottoContesto=OpenData&DB_NAME=n201246&NDFH=440264&TDFH=OPEN1&PRFH=DATASET119&MPFH=1&AEFH=EYIEVSRUENTPKUIGZZEFGVJYCKOLDNOGIYSSGYFWCVDQSWDKUAF1LXQIKMR119NDBLSREBYIAGJL1YOP_N201246F201246&FNFH=dataset_2014_L190.xml,200,1186571,1538
./data/url/2016-02-19_14:00:16/GET.csv:GET,http://asp.urbi.it/urbi/progs/urp/fecore01.sto?CPT=N&FileContesto=UR&SottoContesto=OpenData&DB_NAME=n201246&NDFH=440264&TDFH=OPEN1&PRFH=DATASET119&MPFH=1&AEFH=EYIEVSRUENTPKUIGZZEFGVJYCKOLDNOGIYSSGYFWCVDQSWDKUAF1LXQIKMR119NDBLSREBYIAGJL1YOP_N201246F201246&FNFH=dataset_2014_L190.xml",1,200,1186571,3609
./data/url/2016-02-19_14:00:16/single.csv:00146470471,http://asp.urbi.it/urbi/progs/urp/fecore01.sto?CPT=N&FileContesto=UR&SottoContesto=OpenData&DB_NAME=n201246&NDFH=440264&TDFH=OPEN1&PRFH=DATASET119&MPFH=1&AEFH=EYIEVSRUENTPKUIGZZEFGVJYCKOLDNOGIYSSGYFWCVDQSWDKUAF1LXQIKMR119NDBLSREBYIAGJL1YOP_N201246F201246&FNFH=dataset_2014_L190.xml",1
./data/url/single.csv:00146470471,http://asp.urbi.it/urbi/progs/urp/fecore01.sto?CPT=N&FileContesto=UR&SottoContesto=OpenData&DB_NAME=n201246&NDFH=440264&TDFH=OPEN1&PRFH=DATASET119&MPFH=1&AEFH=EYIEVSRUENTPKUIGZZEFGVJYCKOLDNOGIYSSGYFWCVDQSWDKUAF1LXQIKMR119NDBLSREBYIAGJL1YOP_N201246F201246&FNFH=dataset_2014_L190.xml",1
./ANAC.json:    "URL": "http://asp.urbi.it/urbi/progs/urp/fecore01.sto?CPT=N&FileContesto=UR&SottoContesto=OpenData&DB_NAME=n201246&NDFH=440264&TDFH=OPEN1&PRFH=DATASET119&MPFH=1&AEFH=EYIEVSRUENTPKUIGZZEFGVJYCKOLDNOGIYSSGYFWCVDQSWDKUAF1LXQIKMR119NDBLSREBYIAGJL1YOP_N201246F201246&FNFH=dataset_2014_L190.xml\",1",
```

correcting that line by manually adding an opening quote fixed the problem. We suspect the origin of the problem lies in `ANAC.json`

**Comment by alemela** [comment]
This should have fixed the problem: https://github.com/synapta/public-contracts/commit/5288a55c54fb37b8a12866b13bd03b7fe9c94857
I wait to close until tested on your infrastructure.
